# Generated by Django 3.2.8 on 2021-11-24 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskLable',
            new_name='TaskLabel',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lables',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='tasks.TaskLabel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
