# Generated by Django 3.2.8 on 2021-11-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0007_auto_20211125_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedmodel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='labels.tasklabel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, to='labels.TaskLabel'),
        ),
        migrations.DeleteModel(
            name='TaskLabel',
        ),
    ]
