# Generated by Django 3.2.8 on 2021-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0010_rename_content_task_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelatedModel',
            new_name='TaskLabels',
        ),
    ]
